const AuthTypes = {
  LOGIN_START: '[AUTH] LOGIN START',
  LOGIN_SUCESS: '[AUTH] LOGIN SUCCESS',
  RESET_PASSWORD: '[AUTH] RESET PASSWORD',
  RESET_PASSWORD_SUCCESS: '[AUTH] RESET PASSWORD SUCCESS',
  REQUEST_EMAIL_RESET: '[AUTH] REQUEST EMAIL RESET',
  REQUEST_EMAIL_RESET_SUCCESS: '[AUTH] REQUEST EMAIL RESET SUCCESS',
  AUTH_RESET: '[AUTH] AUTH_RESET',
  AUTH_RESET_SUCCESS: '[AUTH] AUTH_RESET_SUCCESS',
  ERROR: '[AUTH] ERROR',
};

export default AuthTypes;
