const AuthTypes = {
  LOGIN_START: '[AUTH] LOGIN START',
  LOGIN_SUCESS: '[AUTH] LOGIN SUCCESS',
  RESET_PASSWORD: '[AUTH] RESET PASSWORD',
  RESET_PASSWORD_SUCCESS: '[AUTH] RESET PASSWORD SUCCESS',
  ERROR: '[AUTH] ERROR',
};

export default AuthTypes;
