const WalletTypes = {
    ADD_WALLET_START: '[WALLET] ADD_WALLET_START START',
    ADD_WALLET_SUCCESS: '[WALLET] ADD_WALLET_SUCCESS',
    WITHDRAW_WALLET_START: '[WALLET] WITHDRAW_WALLET_START START',
    WITHDRAW_WALLET_SUCCESS: '[WALLET] WITHDRAW_WALLET_SUCCESS',
    GET_ALL_WALLETS: '[WALLET] GET ALL WALLETS',
    GET_ALL_WALLETS_SUCCESS: '[WALLET] GET ALL WALLETS_SUCCESS',
    GET_TRANSACTIONS_BY_WALLET: '[WALLET] GET_TRANSACTIONS_BY_WALLET',
    GET_TRANSACTIONS_BY_WALLET_SUCCESS: '[WALLET] GET_TRANSACTIONS_BY_WALLET_SUCCESS',
    ERROR: '[WALLET] ERROR'
};

export default WalletTypes;