const AuthTypes = {
    SIGNUP_START: '[AUTH] SIGNUP START',
    SIGNUP_SUCCESS: '[AUTH] SIGNUP SUCCESS',
    LOGIN_START: '[AUTH] LOGIN START',
    LOGIN_SUCESS: '[AUTH] LOGIN SUCCESS',
    ERROR: '[AUTH] ERROR'
};

export default AuthTypes;