const AuthTypes = {
    SIGNUP_START: '[AUTH] SIGNUP START',
    SIGNUP_SUCCESS: '[AUTH] SIGNUP SUCCESS',
    LOGIN_START: '[AUTH] LOGIN START',
    LOGIN_SUCESS: '[AUTH] LOGIN SUCCESS',
    AUTO_LOGIN: '[AUTH] AUTO LOGIN',
    RESET_PASSWORD: '[AUTH] RESET PASSWORD',
    RESET_PASSWORD_SUCCESS: '[AUTH] RESET PASSWORD SUCCESS',
    REQUEST_EMAIL_RESET: '[AUTH] REQUEST EMAIL RESET',
    REQUEST_EMAIL_RESET_SUCCESS: '[AUTH] REQUEST EMAIL RESET SUCCESS',
    ENABLE_TWO_AUTH: '[AUTH] ENABLE TWO AUTH',
    ENABLE_TWO_AUTH_SUCCESS: '[AUTH] ENABLE TWO AUTH SUCCESS',
    SEND_CODE_TWO_AUTH: '[AUTH] SEND_CODE_TWO_AUTH',
    SEND_CODE_TWO_AUTH_SUCCESS: '[AUTH] SEND_CODE_TWO_AUTH_SUCCESS',
    ERROR: '[AUTH] ERROR'
};

export default AuthTypes;